import Link from "next/link";
import { CaseHeader } from "@/components/case-header";
import { ConfidenceChip } from "@/components/confidence-chip";
import { OwaspBadge } from "@/components/owasp-badge";
import { SeverityChip, type Severity } from "@/components/severity-chip";
import { SeverityRibbon } from "@/components/severity-ribbon";
import { loadAudit, loadReport } from "@/lib/server";
import type { ReportPayload } from "@/lib/types";
import { tabs } from "../../tabs";

export default async function ReportPage({
  params, searchParams,
}: {
  params: { id: string };
  searchParams: { view?: string };
}) {
  const view = searchParams.view === "technical" ? "technical" : "executive";
  const [audit, payload] = await Promise.all([
    loadAudit(params.id),
    loadReport(params.id, view),
  ]);

  return (
    <>
      <CaseHeader
        caseNo={audit.id.toUpperCase().slice(0, 12)}
        source={audit.source_ref}
        generatedAt={audit.finished_at ?? "—"}
        tabs={tabs(params.id, "report")}
      />

      <div className="mb-8 flex items-center justify-between">
        <ViewSwitch active={view} auditId={params.id} />
        <div className="flex gap-3">
          <ExportLink href={`/api/v1/audits/${params.id}/report?view=${view}&format=pdf`}>report.pdf</ExportLink>
          <ExportLink href={`/api/v1/audits/${params.id}/report?view=${view}&format=md`}>report.md</ExportLink>
          <ExportLink href={`/api/v1/audits/${params.id}/report?view=${view}&format=json`}>report.json</ExportLink>
        </div>
      </div>

      {view === "executive" ? <Executive payload={payload} /> : <Technical payload={payload} />}
    </>
  );
}

function ViewSwitch({ active, auditId }: { active: "executive" | "technical"; auditId: string }) {
  const Item = ({ k, label }: { k: "executive" | "technical"; label: string }) => (
    <Link
      href={`/audits/${auditId}/report?view=${k}`}
      className={`px-4 py-2 font-mono text-[11px] uppercase tracking-widest2 ${
        k === active ? "bg-ink text-bone" : "text-bone-mute hover:text-bone"
      }`}
    >
      [{label}]
    </Link>
  );
  return (
    <div className="flex border border-ink-300">
      <Item k="executive" label="exec" />
      <Item k="technical" label="tech" />
    </div>
  );
}

function ExportLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a
      href={href}
      className="inline-flex items-baseline gap-2 border border-ink-300 px-3 py-2 font-mono text-[11px] uppercase tracking-widest2 text-bone-mute hover:border-signal-live hover:text-signal-live"
    >
      <span aria-hidden className="text-ink-400">$</span>
      cat {children}
    </a>
  );
}

function Executive({ payload }: { payload: ReportPayload }) {
  const sev = payload.summary.severity_breakdown as Record<Severity, number>;
  return (
    <article className="grid grid-cols-12 gap-x-8 gap-y-10">
      <header className="col-span-12 border-b border-ink-300 pb-8">
        <div className="term-label">executive.report</div>
        <h2 className="mt-3 font-display text-[clamp(40px,6vw,84px)] leading-[0.95] tracking-tight">
          <span className="text-bone">a reading of the</span>{" "}
          <span className="italic text-signal-live">risk surface</span>
          <span className="text-bone-ghost">.</span>
        </h2>
      </header>

      <section className="col-span-12 lg:col-span-7">
        {payload.narrative && (
          <p className="font-mono text-[14px] leading-[1.8] text-bone-dim">
            <span className="text-bone-ghost">{"// auditor.narrative"}</span><br />
            {payload.narrative}
          </p>
        )}
        <p className="mt-6 border-l border-ink-300 pl-4 font-mono text-[12px] leading-[1.7] text-bone-mute">
          <span className="text-bone-ghost">{"//"}</span> this narrative is generated by the
          reasoning layer over the normalized finding ledger. it does not introduce new findings
          and omits exploit-shaped content per platform policy.
        </p>
      </section>

      <aside className="col-span-12 lg:col-span-5 space-y-8">
        <div>
          <div className="term-label mb-2">severity.distribution</div>
          <SeverityRibbon breakdown={sev} />
        </div>
        <OwaspTable owasp={payload.summary.owasp_breakdown ?? {}} />
      </aside>

      {payload.top_findings && payload.top_findings.length > 0 && (
        <section className="col-span-12 mt-2 border-t border-ink-300 pt-10">
          <div className="term-label">top_findings()</div>
          <ol className="mt-5">
            {payload.top_findings.map((f, i) => (
              <li
                key={i}
                className="grid grid-cols-[80px_1fr] gap-5 border-b border-ink-300 px-1 py-4 last:border-b-0"
              >
                <span className="pt-2 font-mono text-[11px] tabular text-ink-400">
                  0x{(i * 0x10).toString(16).padStart(6, "0")}
                </span>
                <div>
                  <div className="flex flex-wrap items-baseline gap-3">
                    <SeverityChip severity={f.severity} size="sm" />
                    <h3 className="font-display text-[20px] leading-tight text-bone">{f.title}</h3>
                  </div>
                  <div className="mt-2 flex items-center gap-3 text-bone-mute">
                    <span className="font-mono text-[10px] uppercase tracking-widest2">{f.category}</span>
                    {f.owasp_category && <OwaspBadge category={f.owasp_category} />}
                  </div>
                  {f.business_impact && (
                    <p className="mt-3 max-w-[80ch] font-mono text-[13px] leading-[1.7] text-bone-dim">
                      <span className="text-bone-ghost">{"//"} impact —</span> {f.business_impact}
                    </p>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </section>
      )}
    </article>
  );
}

function Technical({ payload }: { payload: ReportPayload }) {
  return (
    <article>
      <header className="mb-10 border-b border-ink-300 pb-6">
        <div className="term-label">technical.report</div>
        <h2 className="mt-2 font-display text-[44px] leading-tight tracking-tight text-bone">
          findings_register
          <span className="text-bone-ghost">[]</span>
        </h2>
        <p className="mt-3 max-w-[80ch] font-mono text-[12px] leading-[1.7] text-bone-mute">
          <span className="text-bone-ghost">{"//"}</span> deduplicated ledger reproduction. every
          entry traces to one or more scanners. evidence is redacted at the point of capture.
        </p>
      </header>

      <ol className="border-t border-ink-300">
        {payload.findings?.map((f, i) => (
          <li key={f.id} className="grid grid-cols-12 gap-x-6 gap-y-2 border-b border-ink-300 py-6">
            <div className="col-span-12 md:col-span-3 flex flex-col gap-2">
              <span className="font-mono text-[10px] uppercase tracking-widest2 text-bone-ghost">
                <span className="text-ink-400">entry</span> · {String(i + 1).padStart(3, "0")}
              </span>
              <ConfidenceChip confidence={f.confidence} />
            </div>
            <div className="col-span-12 md:col-span-9">
              <div className="flex flex-wrap items-baseline gap-3">
                <SeverityChip severity={f.severity} size="sm" />
                <h3 className="font-display text-[20px] leading-tight text-bone">{f.title}</h3>
              </div>
              <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-[11px] text-bone-mute">
                <span className="uppercase tracking-widest2">{f.category}</span>
                {f.owasp_category && <OwaspBadge category={f.owasp_category} />}
                {f.cwe && <span>· {f.cwe}</span>}
                {f.cve && <span className="text-signal-high">· {f.cve}</span>}
                <span className="text-ink-400">· src=[{f.source_tool.join(",")}]</span>
              </div>
              <p className="mt-3 max-w-[80ch] font-mono text-[13px] leading-[1.7] text-bone-dim">
                <span className="text-bone-ghost">{"//"}</span> {f.explanation}
              </p>
              {f.business_impact && (
                <p className="mt-2 max-w-[80ch] font-mono text-[12px] leading-[1.7] text-bone-mute">
                  <span className="text-bone-ghost">impact ⟶</span> {f.business_impact}
                </p>
              )}
              {f.safe_guidance && (
                <p className="mt-1 max-w-[80ch] font-mono text-[12px] leading-[1.7] text-bone">
                  <span className="text-bone-ghost">guidance ⟶</span> {f.safe_guidance}
                </p>
              )}
              <div className="mt-3 grid grid-cols-1 gap-1 font-mono text-[11px] text-bone-ghost md:grid-cols-2">
                {f.affected_lines.map((al, j) => (
                  <div key={j} className="flex items-baseline justify-between border-t border-ink-300 pt-1">
                    <span className="truncate text-bone-dim">{al.file}</span>
                    <span className="tabular text-bone-mute">
                      L{al.start}{al.end && al.end !== al.start ? `–${al.end}` : ""}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </li>
        ))}
      </ol>
    </article>
  );
}

function OwaspTable({ owasp }: { owasp: Record<string, number> }) {
  const entries = Object.entries(owasp).sort((a, b) => b[1] - a[1]);
  if (!entries.length) return null;
  const total = entries.reduce((s, [, v]) => s + v, 0) || 1;
  return (
    <div>
      <div className="term-label mb-2">owasp.distribution</div>
      <ul className="border border-ink-300">
        {entries.map(([k, v]) => {
          const pct = Math.round((v / total) * 16);
          return (
            <li
              key={k}
              className="grid grid-cols-[1fr_60px_30px] items-center gap-3 border-b border-ink-300 px-3 py-1.5 last:border-b-0"
            >
              <span className="truncate font-mono text-[12px] text-bone-dim">{k}</span>
              <span className="font-mono text-[11px] tabular text-signal-live">
                {"█".repeat(pct)}{"·".repeat(Math.max(0, 16 - pct))}
              </span>
              <span className="text-right font-mono text-[12px] tabular text-bone">{v}</span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
